# Generated by Django 3.0.5 on 2021-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_url', models.URLField()),
                ('token_id', models.URLField()),
                ('access_token', models.CharField(blank=True, max_length=200)),
                ('token_type', models.CharField(blank=True, max_length=200)),
                ('signature', models.CharField(blank=True, max_length=200)),
                ('issued_at', models.BigIntegerField()),
            ],
        ),
    ]
